### ISSUE TITLE
CR checklist

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-method-identifiers#39]
For all Transition Requests, to advance a specification to a new maturity level other than Note, the Working Group:

 * [x] must [record the group's decision to request advancement](https://lists.w3.org/Archives/Public/public-payments-wg/2017Jul/0020.html).
 * [ ] must obtain Director approval.
 * [x] must provide public documentation of all substantive [changes to the technical report](https://github.com/w3c/webpayments-method-identifiers/compare/gh-pages@%7B2016-05-31%7D...gh-pages) since the previous publication.
 * [x] must formally address [all issues](https://github.com/w3c/webpayments-method-identifiers/issues?q=is%3Aissue+is%3Aclosed) raised about the document since the previous maturity level.
 * [x] must provide public documentation of any Formal Objections (**None**)
 * [x] should provide public documentation of [changes](https://github.com/w3c/webpayments-method-identifiers/compare/gh-pages@%7B2016-05-31%7D...gh-pages) that are not substantive.
 * [x] should report which, if any, of the Working Group's requirements for this document have changed since the previous step. (**No requirements have changed**)
 * [x] should report any changes in dependencies with other groups. (**No dependencies have changed**)
 * [x] should provide information about implementations known to the Working Group.
    * Chrome (Android and beginning on desktop), Edge, Facebook, Samsung Internet Browser
    * See also [Caniuse on Payment Request API](https://caniuse.com/#feat=payment-request)
 
To publish a Candidate recommendation, in addition to meeting the general requirements for advancement a Working Group:

 * [x] must show that the specification has met all Working Group requirements, or explain why the requirements have changed or been deferred, (*No requirements have changed*)
    * [Key requirements](https://www.w3.org/2016/09/20-wpwg-minutes#item04) have been met: distributed naming possible (constrained URL syntax), use of URLs to fetch manifest files, small set of standardized short strings for convenience.
 * [x] must document changes to dependencies during the development of the specification, . (**No dependencies have changed**)
 * [x] must [document](https://w3c.github.io/payment-method-id/reports/implementation.html) how adequate implementation experience will be demonstrated,
 * [x] must specify the deadline for comments, which must be at least four weeks after publication, and should be longer for complex documents, (**2017-10-31**)
 * [x] must show that the specification has received wide review, and
        * Reviews by [TAG](https://github.com/w3ctag/design-reviews/issues/152), [PING](https://lists.w3.org/Archives/Public/public-payments-wg/2017Mar/0089.html), [I18N Core](https://www.w3.org/Search/Mail/Public/search?keywords=i18n&hdr-1-name=subject&hdr-1-query=&index-grp=Public_FULL&index-type=t&type-index=public-payments-wg), and input from W3C management
 * [x] may identify features in the document as "at risk". These features may be removed before advancement to Proposed Recommendation without a requirement to publish a new Candidate Recommendation. (**No features at risk**)

**Comment by marcoscaceres** [comment]
@ianbjacobs, would appreciate your help with this one.

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres, @zkoch, @adrianba, @sideshowbarker,

For CR-readiness, the main topics that need some attention are:

* Resolving small number of [open issues](https://github.com/w3c/webpayments-method-identifiers/issues) or marking as editorial or whatever.
* Establishing how we will show interop for validation and comparison of both types of PMIs (URL and short string). I imagine some of that can been demonstrated through tests written elsewhere (e.g., comparison of URLs). What is the plan for a test suite for these features?

**Comment by marcoscaceres** [comment]
@ianbjacobs I added a placeholder for the implementation report: 
https://w3c.github.io/payment-method-id/reports/implementation.html

**Comment by marcoscaceres** [comment]
Ok, all issues addressed (well, PRs sent for them)! 🎉 Now just need "Director Approval".

**Comment by marcoscaceres** [comment]
Actually, still need "must document how adequate implementation experience will be demonstrated,". Need to put something about tests and link to implementation report. The spec contains a link to the implementation report already, but I'ld like something in the SoTD.

**Comment by marcoscaceres** [comment]
About testing, let's just write some tests using the examples I proposed today (using payment request) and "basic-card". I have a few tests locally that we can reuse. 

That should be enough to pass for the purpose of CR.
